kind: pipeline
type: docker
name: default

environment:
  STAGE: dev

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: test
  image: python
  commands:
    - echo "this is $STAGE environment"
    - echo "my name is {{ .input.print }}"
